version: '3.9'
services:
  csgo:
    build: .
    ports:
      - "27015:27015/tcp"
      - "27015:27015/udp"
      - "27020:27020"
    volumes:
      - ./csgo-server:/home/steam/csgo-dedicated
    environment:
      SRCDS_TOKEN: 'F5623473A18B859906789684064C368C'
      SRCDS_RCONPW: 'war'
      SRCDS_PW: 'war'
      SRCDS_HOSTNAME: 'SurfTimer Server'
      SRCDS_TICKRATE: 64
      SRCDS_MAXPLAYERS: 14
      SRCDS_STARTMAP: 'surf_bbb'
      SRCDS_REGION: 3
      SRCDS_GAMETYPE: 0
      SRCDS_GAMEMODE: 1
      METAMOD_VERSION: '1.11'
      SOURCEMOD_VERSION: '1.11'
      DB_HOST: '192.168.1.34'
      DB_PORT: '3306'
      DB_DATABASE: surftimer
      DB_USER: surftimer
      DB_PASS: MMbg6cEqR7VsJ1yVEugp
      SV_DOWNLOADURL: 'https://mukavajoni.kapsi.fi/surf/csgo'
      MAPLIST_URL: 'https://mukavajoni.kapsi.fi/surf/csgo/maps/maplist-dev.php'
      #ZONED_MAPS_ONLY: 1
